# Generated by Django 5.1.2 on 2024-11-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Робота'), ('personal', 'Особисте'), ('study', 'Навчання')], default='personal', max_length=10, verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=10, verbose_name='Пріоритет'),
        ),
    ]
