# Generated by Django 5.1.2 on 2024-11-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_category_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Робота'), ('personal', 'Особисте'), ('study', 'Навчання'), ('other', 'Інше')], default='other', max_length=10, verbose_name='Категорія'),
        ),
    ]
